### PR TITLE
feat(rabbitmq): allow amqplib 0.8.0 range

### PR DESCRIPTION
**Pull request by jeremylvln**
The new Node.js LTS is v16.
`amqplib` 0.7.x requires Node.js `<15`
`amqplib` 0.8.0 removes this constraint and requires `>=10`

This PR allows any project using the RabbitMQ package to use Node LTS again :)

### CODE REVIEW

**Comment by WonderPanda** [comment]
Are there any breaking changes or concerns with us just updating it to 0.8.0 and dropping 0.7?

**Comment by jeremylvln** [comment]
> Are there any breaking changes or concerns with us just updating it to 0.8.0 and dropping 0.7?

I kept the `^0.7.0` range to avoid breaking existing projects. As you can see [here](https://github.com/squaremo/amqp.node/releases/tag/v0.8.0), there is no functional change other than the Node version. If you want me to drop this range, I'll do!

**Comment by WonderPanda** [comment]
I'd rather not support two versions at once. Let's just upgrade it to 0.8

**Comment by jeremylvln** [comment]
> I'd rather not support two versions at once. Let's just upgrade it to 0.8

I've edited the patch, thanks!

**Comment by WonderPanda** [comment]
Hmmm, the build failed looks like the image I was using might be deprecated in Azure Pipelines. Been meaning to switch over to GH Actions for a while but haven't found the time. I'd like to see that all the checks pass before I merge this

**Review by WonderPanda — APPROVED** [review]

**Comment by WonderPanda** [comment]
@IamBlueSlime This is available in @golevelup/nestjs-rabbitmq@1.18.1

**Comment by jeremylvln** [comment]
> @IamBlueSlime This is available in @golevelup/nestjs-rabbitmq@1.18.1

Awesome, work perfectly! Thank you

**Pull request merged**
