### PR TITLE
feat(rabbitmq): add custom logger to configuration

### PR DESCRIPTION
**Pull request by AdrienEtienne**
# Description

This PR is about adding a custom logger, implementing the `LoggerService` interface from NestJS.

## What is done

We pass the logger directly into the configuration object.

## Missing \ Improvements

Currently the class `RabbitMQModule` is still using the default logger. I didn't found a way to pass a custom logger from the configuration. Help would be appreciated :).

## Related PRs

This PR is about allowing to set log level to verbose: https://github.com/golevelup/nestjs/pull/264

I think it is a better solution to just pass a custom logger to the module.

### CODE REVIEW

**Comment by underfisk** [comment]
LGTM, @WonderPanda Any thoughts on this?

**Comment by AdrienEtienne** [comment]
Any update on that?

**Review by WonderPanda — APPROVED** [review]

**Comment by WonderPanda** [comment]
All the integration tests seem to be failing, we'll need to look into this before the PR can be merged

**Comment by AdrienEtienne** [comment]
@WonderPanda do you have any idea why the tests are failing?

**Comment by AdrienEtienne** [comment]
A new e2e test I wrote was failing... I changed that.

**Comment by underfisk** [comment]
@AdrienEtienne The tests seem to be stable and pass now, can you just check the unsafety that's reported on CI nodejs 17? Once that passes, I'm okay to merge

**Comment by AdrienEtienne** [comment]
> @AdrienEtienne The tests seem to be stable and pass now, can you just check the unsafety that's reported on CI nodejs 17? Once that passes, I'm okay to merge

Ok thanks.

The tests are failing randomly when I run those locally. I changed the test on the custom logger, got no error with node v17.
But still have tests failing sometimes, no matter which version of node I am using.

**Pull request merged**
