### PR TITLE
Replace ConsoleLogger with Logger so it can be replaced by an external logger

### PR DESCRIPTION
**Pull request by shakedo**
This PR is for solving this issue: https://github.com/golevelup/nestjs/issues/379

### CODE REVIEW

**Review by WonderPanda — APPROVED** [review]
This looks fine to me. @IamBlueSlime @underfisk do you know if there was a particular reason we switched to using ConsoleLogger instead as part of the upgrade to Nest 8?

**Comment by jeremylvln** [comment]
No idea about this change, I didn't do it personally.

**Comment by underfisk** [comment]
@WonderPanda Since v8 `Logger` is now deprecated, `ConsoleLogger` is the new standard logger, I don't think we should revert because the reason behind the issue was that there was no way of customizing the logger using `ConsoleLogger` but there is, extending the logger is not tied to the any specific class such as `Logger`

**Review by underfisk — CHANGES_REQUESTED** [review]
This is a regression and there's no need for us to use deprecated services

**Comment by WonderPanda** [comment]
Indeed it seems like this is the way forward as of Nest 8: https://docs.nestjs.com/migration-guide#logger-breaking-changes

**Pull request closed without merging**
