### PR TITLE
Fix/nest js freeze on rabbit rpc annotation

### PR DESCRIPTION
**Pull request by vijay94**

### CODE REVIEW

**Comment by vijay94** [comment]
@WonderPanda Can you verify this PR?

**Comment by WonderPanda** [comment]
@vijay94 Is there a way for us to get some e2e test coverage to verify that this is working as expected? I'm wary of untested changes especially since it seems like the last attempt at fixing this problem didn't actually work

**Comment by vijay94** [comment]
@WonderPanda I can explore on e2e test. But this change is not a tested one. We had two annotations namely RabbitSubscribe and RabbitRPC. The last PR only fixed the RabbitSubscribe annotation. We missed out the RabbitRPC annotation.

**Comment by vijay94** [comment]
> @vijay94 Is there a way for us to get some e2e test coverage to verify that this is working as expected? I'm wary of untested changes especially since it seems like the last attempt at fixing this problem didn't actually work

Hi @WonderPanda Added e2e test to test endpoints when rabbitmq connection is not available.

**Comment by vijay94** [comment]
@underfisk Can we publish a new version with this change?

**Comment by underfisk** [comment]
@vijay94 I don't have permissions to publish but i believe that @WonderPanda will publish a new version soon

**Comment by WonderPanda** [comment]
@vijay94 I published new package versions this morning

**Pull request merged**
