### PR TITLE
feat(graphql-request): update graphql and graphql-request packages

### PR DESCRIPTION
**Pull request by GauthierD-**
## What's new?

- Update package `graphql@^16.8.1` (latest)
- Update package `graphql-request@^6.1.0` (latest)

## Why ?

- It always cool to be up to date 🚀 
- We need to update these packages to avoid issues with Node LTS (20.9.0) 
Screenshot 2023-11-20 at 5 57 49 PM

### CODE REVIEW

**Comment by underfisk** [comment]
@GauthierD- Can you confirm that within the version range there are no breaking changes?

**Comment by GauthierD-** [comment]
hello @underfisk 

Here you can find the breaking changes for these 2 packages

### Graphql-request
- Official support for Node 12 is dropped
- bring TS 5 support
- remove file uploads feature 
- Invoke responseMiddleware in error cases as well

### graphql-js
- The huge list => https://github.com/graphql/graphql-js/releases/tag/v16.0.0

if my PR is accepted, I think the package `@golevel/nest-graphql-request` must be released with a major version =/

**Comment by underfisk** [comment]
> hello @underfisk
> 
> Here you can find the breaking changes for these 2 packages
> 
> ### Graphql-request
> * Official support for Node 12 is dropped
> * bring TS 5 support
> * remove file uploads feature
> * Invoke responseMiddleware in error cases as well
> 
> ### graphql-js
> * The huge list => https://github.com/graphql/graphql-js/releases/tag/v16.0.0
> 
> if my PR is accepted, I think the package `@golevel/nest-graphql-request` must be released with a major version =/

Hi, thanks for listing it.
Yes my main concern was about launching a major, we've got quite a few changes that are pending a release but i don't have permission to do so. After that release I'm fine having this PR merged and launch a new major version for the graphql request package

**Comment by GauthierD-** [comment]
@underfisk thx for your answer

Do you know when the next major release is scheduled? I assume we're not the only team experiencing issues with this package when used with Node@20.9.0 (the current LTS)

**Comment by underfisk** [comment]
@WonderPanda may be able to answer you on that one, as i mentioned earlier i do not have control over releases

**Comment by WonderPanda** [comment]
> @underfisk thx for your answer
> 
> Do you know when the next major release is scheduled? I assume we're not the only team experiencing issues with this package when used with Node@20.9.0 (the current LTS)

I think its fine for us to just ship a new major for this. The packages are super out of date. Thanks for the contribution

**Comment by WonderPanda** [comment]
@GauthierD- Since we haven't hit a 1.x release before this is a minor update:

```
@golevelup/nestjs-graphql-request: 0.1.16 => 0.2.0
```

Please try out 0.2.0 and let us know if everything is in working order for you

**Comment by GauthierD-** [comment]
@WonderPanda We still have an error, we don't know why.... Because when we downlaod the package from Github + local build + npm link we have 0 issues but with the package from npm, we have the same error.

We'll try to reproduce our error with a small stack and I'll come back here if I find something

**Pull request merged**
