### PR TITLE
feat(add_header_decorator): @RabbitHeader() decorator added

### PR DESCRIPTION
**Pull request by muhammadzadeh**
now we can access provided headers inside consumers

```
@RabbitRPC({
        exchange: 'transaction_exchange',
        routingKey: 'transaction.find.all',
        queue: 'transaction_find_all_queue',
        errorBehavior: MessageHandlerErrorBehavior.ACK,
        errorHandler: ReplyErrorCallback,
    })
    @UseGuards(AccessGuard)
    public async pubSubHandler(
        @RabbitPayload() data: dataDto,
        @RabbitHeader() headers: headerDto,
    ) {  
              
    }
```

### CODE REVIEW

**Comment by WonderPanda** [comment]
@muhammadzadeh This seems like a good addition but can you take a look at the failing tests caused by these changes?

**Comment by muhammadzadeh** [comment]
@WonderPanda  It seems that arrived data inside custom ValidationPipe is always undefined, so always throw `RpcException('expected number as payload');`. any advice?

**Comment by muhammadzadeh** [comment]
@WonderPanda Tests are passed. The problem is with the wrong index inside RabbitRpcParamsFactory.

**Comment by muhammadzadeh** [comment]
@WonderPanda Tests are passed.

**Comment by sezanzeb** [comment]
Is there any documentation about @RabbitHeader and such anywhere?

Edit: https://github.com/golevelup/nestjs/tree/master/packages/rabbitmq#golevelupnestjs-rabbitmq (though RabbitHeader is not mentioned there)

**Comment by muhammadzadeh** [comment]
@sezanzeb sorry for delay
look at this sample
`   
 async sendEvent(sendEventDto: SendEventDto) {
        return await this.amqpConnection.request(
            {
                exchange: sendEventDto.exchange,
                routingKey: sendEventDto.routeKey,
                payload: sendEventDto.message,
                headers: {
                    'x-user': JSON.stringify({ id: 1, role: 'ADMIN' })
                }
            }
        );
    }
`

`
@RabbitRPC({
        exchange: 'referral_exchange',
        routingKey: 'referral.code.create',
        queue: 'referral_code_create_queue',
        errorBehavior: MessageHandlerErrorBehavior.ACK,
        errorHandler: ReplyErrorCallback,
    })
    @UseGuards(AccessGuard)
    async consume(
        @RabbitHeader('x-user', new ParseJsonPipe()) user: User,
        @RabbitPayload() createDto: CreateCodeDto,
    ) {
        const item = await this.codesService.createOne(createDto, user);
        return new CodeResponse(item);
    }
`

**Comment by sezanzeb** [comment]
don't worry, thanks. Yeah, makes sense, now that I'm familiar with the regular nestjs decorators in more detail the code is pretty self explanatory actually.

**Comment by sezanzeb** [comment]
Though it may make sense to mention them in the docs, so that people know about the feature

**Pull request merged**
