### PR TITLE
chore: bump stripe version to 14.19.0

### PR DESCRIPTION
**Pull request by fermentfan**
I noticed my local build fails due to the version conflict. I didn't try it out locally yet so I wonder if there is more work involved than just bumping it?

### CODE REVIEW

**Comment by fermentfan** [comment]
Seems like the CI/CD is a bit flaky? It failed due to a timeout in a test and locally everything works as expected. Can somebody help me out by retriggering it?

**Comment by mhmdjaw** [comment]
When is this going to be released? The latest version (0.6.5) is still using stripe v11.

**Comment by underfisk** [comment]
@WonderPanda Is it possible to have a major release for Stripe package?

**Comment by WonderPanda** [comment]
> @WonderPanda Is it possible to have a major release for Stripe package?

I just tried to do a release but Stripe isn't set up for a major release yet:

```
Changes:
 - @golevelup/nestjs-stripe: 0.6.5 => 0.6.6
 - @golevelup/ts-jest: 0.4.0 => 0.5.0
 - @golevelup/ts-vitest: 0.4.0 => 0.5.0
 ```

With the current setup with [Conventional Commit there needs to be a commit message that indicates a breaking change](https://www.conventionalcommits.org/en/v1.0.0/#summary) in order for the major version to get bumped

**Comment by oldschoolbg** [comment]
Just wondering if there has been any movement on getting this released?

:)

**Comment by fermentfan** [comment]
Is all we need really just a commit? If so I will open a PR :D

**Comment by fermentfan** [comment]
I hope it works that way? @WonderPanda @underfisk https://github.com/golevelup/nestjs/pull/714

**Comment by WonderPanda** [comment]
This is published as version 0.7.0

**Pull request merged**
