### PR TITLE
fix(rabbitmq): return consumerTag when creating subscriber

### LINKED ISSUE #755: RabbitMQ - returning `consumerTag` when creating subscribers
There seems to be a promise resolve issue about [createSubscriber](https://github.com/golevelup/nestjs/blob/master/packages/rabbitmq/src/amqp/connection.ts#L437) method that prevents `consumerTag` to return in success callback.

Is there any other way to retrieve the consumerTag to use for cancelling/resuming specific consumers?

```typescript
  public async createSubscriber<T>(
    handler: SubscriberHandler<T>,
    msgOptions: MessageHandlerOptions,
    originalHandlerName: string,
    consumeOptions?: ConsumeOptions
  ): Promise<SubscriptionResult> {
    return new Promise((res) => {
      let result: SubscriptionResult;
      this.selectManagedChannel(msgOptions?.queueOptions?.channel)
        .addSetup(async (channel) => {
          const consumerTag = await this.setupSubscriberChannel<T>(
            handler,
            msgOptions,
            channel,
            originalHandlerName,
            consumeOptions
          );
          result = { consumerTag };
        })
        .then(() => {
          res(result);
        });
    });
  }
```

PS. I'd like to contribute by opening a pr that fixes this issue if the intended behavior is as expected.

### PR DESCRIPTION
**Pull request by gunesyu**
fix #755

### CODE REVIEW

**Comment by underfisk** [comment]
@gunesyu May we have tests to reflect this bugfix?

**Comment by gunesyu** [comment]
> @gunesyu May we have tests to reflect this bugfix?

thanks @underfisk , updated with a new commit includes tests for both `createSubscriber` and `createRpc`

**Comment by gunesyu** [comment]
@underfisk needed a rebase to update the branch

**Comment by lzw1926** [comment]
@underfisk  Looking forward the new release contain this PR ASAP, which seems to fixed a bug I encountered when I use the following configuration. The custom direct exchange won't be setup correctly and the relevant channel throw errors.

And when I introduce the local build package with the current master code to my project, everything works just fine !

````ts
exchanges: [
  {
    name: DIRECT_EXCHANGE,
    type: 'direct',
  },
],
connectionInitOptions: {
  wait: false,
},
````

**Comment by underfisk** [comment]
> @underfisk Looking forward the new release contain this PR ASAP, which seems to fixed a bug I encountered when I use the following configuration. The custom direct exchange won't be setup correctly and the relevant channel throw errors.
> 
> And when I introduce the local build package with the current master code to my project, everything works just fine !
> 
> ```ts
> exchanges: [
>   {
>     name: DIRECT_EXCHANGE,
>     type: 'direct',
>   },
> ],
> connectionInitOptions: {
>   wait: false,
> },
> ```

The releases are handled by @WonderPanda

**Comment by SnakeDrak** [comment]
It seems this PR is reopening https://github.com/golevelup/nestjs/issues/494 @underfisk

**Comment by underfisk** [comment]
@gunesyu Would you be able to review this regression and possibly help with a fix 🙏 ?

**Pull request merged**
