### PR TITLE
fix(rabbitmq): add missing queue options

### PR DESCRIPTION
**Pull request by WonderPanda**

### CODE REVIEW

**Review by ssilve1989 — APPROVED** [review]

**Comment by ssilve1989** [comment]
Any update on this one? Not having this causes TS builds to fail 
```
@studio/quote: src/app.service.ts:52:7 - error TS2322: Type '{ autoDelete: boolean; durable: boolean; }' is not assignable to type 'QueueOptions'.
@studio/quote:   Object literal may only specify known properties, and 'autoDelete' does not exist in type 'QueueOptions'.
@studio/quote: 52       autoDelete: true,
@studio/quote:          ~~~~~~~~~~~~~~~~
@studio/quote:   ../../../node_modules/@golevelup/nestjs-rabbitmq/lib/rabbitmq.interfaces.d.ts:30:5
@studio/quote:     30     queueOptions?: QueueOptions;
@studio/quote:            ~~~~~~~~~~~~
@studio/quote:     The expected type comes from property 'queueOptions' which is declared here on type 'Pick<RabbitHandlerConfig, "queue" | "queueOptions" | "exchange" | "routingKey" | "errorBehavior">'
```

**Comment by WonderPanda** [comment]
Hey @ssilve1989 thanks for drawing my attention back to this and sorry that there's been a bit of instability across some issues. I recently transitioned this from a repo on my personal GitHub to the @golevelup org with the intention of trying to encourage more OSS involvement but it seems some things were missed during the transition.

I'll publish a fix for this tonight

**Comment by ssilve1989** [comment]
Thanks!

**Comment by WonderPanda** [comment]
@ssilve1989 This is live now with  `@golevelup/nestjs-rabbitmq@1.7.3`

**Pull request merged**
