### PR TITLE
chore(rabbitmq): amqp libs update

### LINKED ISSUE #542: Bump amqplib dependency to avoid bluebird
The rabbitmq package adds amqplib^0.8.0 dependency, which is dependent on bluebird. Either use amqplib as peerDependency or update the version please

### PR DESCRIPTION
**Pull request by witem**
Update `amqplib` and `amqp-connection-manager` to the latest version.
There are many fixes and improvements.

Similar to https://github.com/golevelup/nestjs/pull/459 and https://github.com/golevelup/nestjs/pull/563
Will close #542 

BREAKING CHANGES
We will no longer emit a disconnect event on an 
initial connection failure - instead we now emit connectFailed on each
connection failure, and only emit disconnect when we transition from
connected to disconnected.

### CODE REVIEW

**Comment by underfisk** [comment]
I'm down for pushing this but it would have to be a major release as we're adding breaking changes. @WonderPanda

**Comment by jarpoole** [comment]
Documented another key bug that would be fixed by upgrading `amqp-connection-manager` to v4 in https://github.com/golevelup/nestjs/issues/647. If there is still work to be done besides the major version change I'm happy to help out!

**Comment by underfisk** [comment]
> Documented another key bug that would be fixed by upgrading `amqp-connection-manager` to v4 in #647. If there is still work to be done besides the major version change I'm happy to help out!

Feel free to help this branch get across the finish line, if the merge conflicts get resolved and the test updated (if needed) I'll gladly push this and release it as part of the next major version

**Comment by ttshivers** [comment]
Why was this closed?

**Pull request closed without merging**
