### PR TITLE
feat(rabbitmq): add rabbitmq message handling

### PR DESCRIPTION
**Pull request by bakedChicken**
These changes allow you to use user-defined parser and serializer for messages passed through RabbitMQ.

### CODE REVIEW

**Comment by WonderPanda** [comment]
@bakedChicken This looks like a really cool addition to the library however it's breaking some of the integration test suite right now so I can't merge until that's green

**Comment by bakedChicken** [comment]
Hello. I fixed CI.

**Comment by bakedChicken** [comment]
@WonderPanda Hello, I have resolved a conflict and now wonder why quality checks are not passing in files I did not touch.

image

**Comment by WonderPanda** [comment]
Hey @bakedChicken Sorry about the delays on this one I know you've been very persistent. I will take a look at this after work tonight and fix the quality checks for you so that we can get custom serialization/deserialization functionality into the library

**Comment by bakedChicken** [comment]
@WonderPanda Thank you! I will wait.

**Comment by WonderPanda** [comment]
@bakedChicken I needed to rebase this code onto the new changes that have been merged since it was opened and I also want to do a little bit of cleanup/modification before this is released. I'm closing this in favor of #135 so that I can help get it finished.

You'll still receive the credit and contribution stats for the repository, thanks for your help on this!

**Pull request closed without merging**
