### PR TITLE
fix(rabbitmq): fix unawaited promises

### PR DESCRIPTION
**Pull request by ttshivers**
I noticed some floating promises in the code when trying to debug an issue due to ordering. Ensuring all the promises are awaited where expected should help prevent possible issues like ensureing the assertExchange is done before trying to bind a queue to it.

### CODE REVIEW

**Comment by underfisk** [comment]
@ttshivers Thank you for this change! Would you be down to write some test coverage to assert what you're describing/what we're trying to accomplish here?

**Comment by ttshivers** [comment]
> @ttshivers Thank you for this change! Would you be down to write some test coverage to assert what you're describing/what we're trying to accomplish here?

I have written a test that fails before my fix and passes after my fix which exposes one of the race conditions that is possible by not awaiting the promises.

**Review by underfisk — APPROVED** [review]

**Comment by underfisk** [comment]
@ttshivers could you update the branch and fix conflicts?

**Comment by ttshivers** [comment]
> @ttshivers could you update the branch and fix conflicts?

I have resolved the conflicts

**Pull request merged**
