### PR TITLE
chore(nestjs-graphql-request): bump graphql-request packages v7.0.1

### LINKED ISSUE #738: golevelup/nestjs-graphql-request: update dependencies graphql-request@7.0.1
there is a new Major version for https://github.com/jasonkuhrt/graphql-request (v7.0.1)

I'll create a Pull request to update this package into @golevelup/nestjs-graphql-request

### PR DESCRIPTION
**Pull request by GauthierD-**
The package nestjs-graphql-request utilizes graphql-request, and a new version (v7.0.1) has been released. As a result of this major version update (v6 -> v7), I am also updating nestjs-graphql-request to v1.0.0.

Please be aware that this update includes breaking changes. The two primary changes are the discontinuation of support for CommonJS and the removal of the cross-fetch polyfill. A comprehensive list of the breaking changes can be found here:

https://github.com/jasonkuhrt/graphql-request/releases/tag/7.0.0

closes #738

### CODE REVIEW

**Comment by GauthierD-** [comment]
Dunno why the CI fail, if someone has an idea feel free to share

On my local machine:
Screenshot 2024-05-21 at 7 37 38 PM
Screenshot 2024-05-21 at 7 37 45 PM

**Comment by underfisk** [comment]
@GauthierD- Could you re-generate `yarn.lock`? It doesn't seem to be able to find `graphql-request` for some reason

**Comment by GauthierD-** [comment]
Hello @underfisk I can now reproduce this error, I guess it's related to [that](https://github.com/jasonkuhrt/graphql-request#typescript-setup) =/

```
TypeScript Setup
This package uses [package.exports] (https://www.typescriptlang.org/docs/handbook/modules/reference.html#packagejson-exports). Therefore if you are a > TypeScript user you must:

have your tsconfig.json moduleResolution set to ["bundler"](https://www.typescriptlang.org/docs/handbook/modules/reference.html#bundler) or ["node16"/"nodenext"](https://www.typescriptlang.org/docs/handbook/modules/reference.html#node16-nodenext-1).
Have your package.json type set to "module".
```

I'll try something but I'm not an expert of Lerna wish me luck 🍀

**Comment by GauthierD-** [comment]
I fixed the build but now the problem is related to jest (ts-jest) =/
I think I'll close this PR for now and if someone have time they can finish the job 👌

**Pull request closed without merging**
