### PR TITLE
feat(rabbitmq): adds additional queue options for rpc

### PR DESCRIPTION
**Pull request by vaidashi**

### CODE REVIEW

**Comment by WonderPanda** [comment]
@vaidashi Good catch! Thanks for the contribution. I'll merge this now and try and publish a new package version today

**Review by WonderPanda — APPROVED** [review]

**Comment by vaidashi** [comment]
thanks @WonderPanda , do you know if you'll be able to publish the new package either today or tomorrow?

**Comment by WonderPanda** [comment]
@vaidashi Yes I'll push a new package version this evening

**Comment by vaidashi** [comment]
awesome

**Comment by WonderPanda** [comment]
@vaidashi The new package (1.4.0) is available now. Thanks again for the contribution

**Pull request merged**
