### PR TITLE
feat(rabbitmq): extend custom parsers, update docs

### LINKED ISSUE #574: Undefined message in rmq if allowNonJsonMessages flag is set to true
Hello,
Before I start I wanted to say this package helped me lots when integrating with RMQ in NestJS, so really appreciate it!

Today I stumbled on a problem that if I don't pass JSON serialisable message, there is no message and it seems that `RabbitPayload()` decorator doesn't work anymore in such case. I was struggling with getting around it until I checked [what happens in the code](https://github.com/golevelup/nestjs/blob/master/packages/rabbitmq/src/amqp/connection.ts#L590)
While I appreciate the type checking, I feel that if the flag `allowNonJsonMessages: true` is provided, the message should be returned as-is, or better yet (in my case), there could be an ability to provide your own parser - by default `JSON.parse` - so in the end it is a valid JS object.

Let me know what you think! If I find some time I could try and implement it

### PR DESCRIPTION
**Pull request by sdomagala**
Closes #574

### CODE REVIEW

**Review by underfisk — APPROVED** [review]
LGTM

**Review by WonderPanda — APPROVED** [review]

**Comment by WonderPanda** [comment]
@sdomagala This looks like a welcome change and I love the improvements to the docs but its currently failling the build for some Typescript errors

**Comment by sdomagala** [comment]
@underfisk thanks!

@WonderPanda yeah sorry about that, I didn't check the ci commands and had some issues running the build, I thought changes were simple enough but was wrong apparently ;) Should be fixed now, commands succeeded on my local machine, can you take another look?

**Comment by sdomagala** [comment]
That took way too many tries so I finally configured e2e setup and should be good now, e2e:

> Test Suites: 12 passed, 12 total
Tests:       65 passed, 65 total
Snapshots:   0 total
Time:        17.498 s, estimated 18 s
Ran all test suites.

And unit tests:
> Test Suites: 11 passed, 11 total
Tests:       70 passed, 70 total
Snapshots:   0 total
Time:        8.446 s
Ran all test suites in 6 projects.
✨  Done in 9.45s.

**Comment by sdomagala** [comment]
Previous test failed on some random timeout that wasn't even something I touched 😅  I think rerun would fix it but I changed e2e tests to timeout after 10sec to be more consistent

**Comment by WonderPanda** [comment]
@sdomagala Thanks for this contribution! This is available now on NPM `@golevelup/nestjs-rabbitmq@3.6.0`

**Comment by sdomagala** [comment]
Perfect, thanks!

**Pull request merged**
